name: C++ CI in ubuntu

on: 
  push:
    branches:
      - '*' 
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu-mingw:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir ./build && cd ./build && cmake ..
    - name: build with gcc
      run: cd ./build && make CAObotPlugin